version: "3.5"
services:
  web-server:
    image: grafana/grafana
    container_name: mygrafana
    volumes:
      - /opt/grafana/lib:/var/lib/grafana
      - /opt/grafana/datasources:/etc/grafana/datasources
      - /opt/grafana/dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    restart: unless-stopped
volumes:
  grafana-data:
